name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        elixir: ["1.14", "1.15"]
        otp: ["25", "26"]
        clickhouse: ["23.3.7.5"]
        include:
          - elixir: "1.15"
            otp: "26"
            clickhouse: "23.3.7.5" 
            timezone: "Europe/Berlin"

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:${{ matrix.clickhouse }}-alpine
        ports:
          - 8123:8123
          - 9000:9000
        env:
          TZ: ${{ matrix.timezone || 'UTC' }}
          options: >-
            --health-cmd nc -zw3 localhost 8124
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-refs/heads/master-

      - run: mix deps.get
      - run: mix format --check-formatted
        if: matrix.elixir == '1.15'
      - run: mix compile --warnings-as-errors
      - run: mix test
