name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:23.3.7.5-alpine
        ports:
          - 8123:8123
          - 9000:9000
        env:
          options: >-
            --health-cmd nc -zw3 localhost 8124
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    strategy:
      matrix:
        elixir: ["1.14"]
        otp: ["25", "26"]

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-refs/heads/master-

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test

      - run: curl https://clickhouse.com/ | sh
      - run: sudo ./clickhouse install
      - run: clickhouse-client --version
      - run: mix test --include clickhouse_client

      # - run: INTEGRATION=1 mix test
